backend:
  name: github
  repo: Kihsu3d/Kihsu3d
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "anime"
    label: "Láminas 3D — Anime"
    folder: "content/anime"
    create: true
    fields:
      - {label: "Nombre", name: "name", widget: "string"}
      - {label: "Precio", name: "price", widget: "string"}
      - {label: "Imagen", name: "image", widget: "image"}

  - name: "kpop"
    label: "Láminas 3D — Kpop"
    folder: "content/kpop"
    create: true
    fields:
      - {label: "Nombre", name: "name", widget: "string"}
      - {label: "Precio", name: "price", widget: "string"}
      - {label: "Imagen", name: "image", widget: "image"}

  - name: "peliculas"
    label: "Láminas 3D — Películas"
    folder: "content/peliculas"
    create: true
    fields:
      - {label: "Nombre", name: "name", widget: "string"}
      - {label: "Precio", name: "price", widget: "string"}
      - {label: "Imagen", name: "image", widget: "image"}

  - name: "musica"
    label: "Láminas 3D — Música"
    folder: "content/musica"
    create: true
    fields:
      - {label: "Nombre", name: "name", widget: "string"}
      - {label: "Precio", name: "price", widget: "string"}
      - {label: "Imagen", name: "image", widget: "image"}

  - name: "series"
    label: "Láminas 3D — Series"
    folder: "content/series"
    create: true
    fields:
      - {label: "Nombre", name: "name", widget: "string"}
      - {label: "Precio", name: "price", widget: "string"}
      - {label: "Imagen", name: "image", widget: "image"}

  - name: "videojuegos"
    label: "Láminas 3D — Videojuegos"
    folder: "content/videojuegos"
    create: true
    fields:
      - {label: "Nombre", name: "name", widget: "string"}
      - {label: "Precio", name: "price", widget: "string"}
      - {label: "Imagen", name: "image", widget: "image"}

  - name: "llaveros"
    label: "Llaveros Personalizados"
    folder: "content/llaveros"
    create: true
    fields:
      - {label: "Nombre", name: "name", widget: "string"}
      - {label: "Precio", name: "price", widget: "string"}
      - {label: "Imagen", name: "image", widget: "image"}

  - name: "figuras"
    label: "Figuras Personalizadas"
    folder: "content/figuras"
    create: true
    fields:
      - {label: "Nombre", name: "name", widget: "string"}
      - {label: "Precio", name: "price", widget: "string"}
      - {label: "Imagen", name: "image", widget: "image"}

  - name: "laminaspersonal"
    label: "Láminas Personalizadas"
    folder: "content/laminaspersonal"
    create: true
    fields:
      - {label: "Nombre", name: "name", widget: "string"}
      - {label: "Precio", name: "price", widget: "string"}
      - {label: "Imagen", name: "image", widget: "image"}
